### ISSUE TITLE
Hook directly into minitest calls ?

### ISSUE THREAD

**Issue by grosser** [jeremyevans/minitest-global_expectations#1]
I'm currently using this to get global expectations back https://github.com/grosser/maxitest/blob/master/lib/maxitest/global_must.rb
I though this might be better because it would catch any newly added method too ... do you see any downside ?

@jeremyevans

**Comment by jeremyevans** [comment]
@grosser Sorry for the long delay, I'm not sure why I missed the notification for this.  In general, that approach seems fine.  I would prefer not to modify Module (though apparently that's what minitest itself does).
